AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Amazon Relational Database Service (RDS) for PostgreSQL. (qs-1saaatk22)
Metadata:
  LICENSE: Apache License Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network configuration
      Parameters:
      - VPCID
      - Subnet1ID
      - Subnet2ID
      - CustomDBSecurityGroup
    - Label:
        default: Database configuration
      Parameters:
      - DBName
      - DBAutoMinorVersionUpgrade
      - DBAllowMajorVersionUpgrade
      - DBBackupRetentionPeriod
      - DBEngineVersion
      - DBInstanceClass
      - DBUsername
      - DBPassword
      - DBPort
      - DBAccessCIDR
      - DBMultiAZ
      - DBAllocatedStorageEncrypted
      - DBExportLogToCloudwatch
      - EnableEventSubscription
      - NotificationList
    - Label:
        default: Database tags (optional)
      Parameters:
      - EnvironmentStage
      - Application
      - ApplicationVersion
      - ProjectCostCenter
      - Confidentiality
      - Compliance
    ParameterLabels:
      DBAllocatedStorage:
        default: Amount of storage (in gigabytes)
      DBName:
        default: Database name
      DBEngineVersion:
        default: Database Engine Version
      DBAllocatedStorageEncrypted:
        default: Database encryption enabled
      DBExportLogToCloudwatch:
        default: Export Database Log to Cloudwatch
      DBAutoMinorVersionUpgrade:
        default: Database auto minor version upgrade
      DBBackupRetentionPeriod:
        default: Database backup retention period
      DBInstanceClass:
        default: Database instance class
      DBUsername:
        default: Username
      DBPassword:
        default: Password
      DBPort:
        default: Database port
      DBAccessCIDR:
        default: Database connection CIDR
      DBMultiAZ:
        default: Multi-AZ deployment
      Subnet1ID:
        default: Private subnet 1 ID
      Subnet2ID:
        default: Private subnet 2 ID
      VPCID:
        default: VPC ID
      CustomDBSecurityGroup:
        default: Custom security group ID
      EnableEventSubscription:
        default: Enable Event Subscription
      NotificationList:
        default: SNS notification email
      EnvironmentStage:
        default: Environment stage
      Application:
        default: Application name
      ApplicationVersion:
        default: Application version
      Compliance:
        default: Compliance classifier
      Confidentiality:
       default: Confidentiality classifier
      ProjectCostCenter:
       default: Project cost center
  cfn-lint:
    config:
      ignore_checks:
        - E9101
      ignore_reasons:
        - E9101: Not applicable as AWS::RDS::DBInstance has properties called “MasterUsername” and “MasterUserPassword
Mappings:
  DBFamilyMap:
    "9.6.20":
      "family": "postgres9.6"
    "9.6.21":
      "family": "postgres9.6"
    "9.6.22":
      "family": "postgres9.6"
    "10.15":
      "family": "postgres10"
    "10.16":
      "family": "postgres10"
    "10.17":
      "family": "postgres10"
    "11.10":
      "family": "postgres11"
    "11.11":
      "family": "postgres11"
    "11.12":
      "family": "postgres11"
    "12.5":
      "family": "postgres12"
    "12.6":
      "family": "postgres12"
    "12.7":
      "family": "postgres12"
    "13.1":
      "family": "postgres13"
    "13.2":
      "family": "postgres13"
    "13.3":
      "family": "postgres13"
Conditions:
  EventSubscription: !Equals [!Ref EnableEventSubscription, 'true']
  DoCreateDatabase: !Not [!Equals [!Ref DBName, '']]
  DBProvisionedIops: !Equals [!Ref DBStorageType, io1]
  UseEnhancedMonitoring: !Not [!Equals [!Ref DBMonitoringInterval, 0]]
  UseDatabaseEncryption: !Equals [!Ref DBAllocatedStorageEncrypted, 'true']
  EnableDBLogExport: !Equals [!Ref DBExportLogToCloudwatch, 'true']
  CreateSecurityGroup: !Equals [!Ref CustomDBSecurityGroup, '']
Parameters:
  DBAllocatedStorage:
    Default: 100
    Description: Amount of storage (in gigabytes)
    Type: Number
  DBMaxAllocatedStorage:
    Default: 1000
    Description: The upper limit in gigabytes to which Amazon RDS can automatically scale the storage
    Type: Number
  DBAllocatedStorageEncrypted:
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Whether or not to encrypt the database.
    Type: String
  DBIops:
    Default: 3000
    ConstraintDescription: Must be in the range 1,000 - 256,000 IOPS
    Description: Must be in the range of 1,000 - 256,000 IOPS
    MinValue: 1000
    MaxValue: 256000
    Type: Number
  DBExportLogToCloudwatch:
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Whether or not to export Database logs to Cloudwatch
    Type: String
  DBAutoMinorVersionUpgrade:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
    Description: Select true to set up auto minor version upgrade.
    Type: String
  DBAllowMajorVersionUpgrade:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
    Description: Select true to set up major version upgrade.
    Type: String
  DBBackupRetentionPeriod:
    Default: 35
    Description: The number of days for which automatic database snapshots are retained.
    Type: String
  DBEngineVersion:
    Description: Select Database Engine Version
    Type: String
    Default: 13.3
    AllowedValues:
      - 9.6.20
      - 9.6.21
      - 9.6.22
      - 10.15
      - 10.16
      - 10.17
      - 11.10
      - 11.11
      - 11.12
      - 12.5
      - 12.6
      - 12.7
      - 13.1
      - 13.2
      - 13.3
  DBInstanceClass:
    AllowedPattern: ^db\.[a-z0-9]+\.[a-z0-9]+$
    ConstraintDescription: Must select a valid database instance type.
    Default: db.m6g.large
    Description: The name of the compute and memory capacity class of the database instance.
    Type: String
  DBAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for external access (use VPC CIDR).
    Type: String
    Default: 10.0.0.0/16
  DBPassword:
    Type: String
    Description: The database admin account password.
    AllowedPattern: ^[^/'\"@]+$
    ConstraintDescription: >-
      8 to 128 printable ASCII characters. Can''t contain any of the following:
      slash (/), single quote (''), double quote ("), or at sign (@).
    MinLength: 8
    MaxLength: 64
    NoEcho: True
  DBUsername:
    Type: String
    Description: The database admin account username.
    MinLength: 1
    MaxLength: 16
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9]*$
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
    Default: pgadmin
  DBMonitoringInterval:
    AllowedValues:
      - 0
      - 1
      - 5
      - 15
      - 30
      - 60
    Default: 60
    Description: Enhanced Monitoring metrics interval in seconds. To disable Enhanced Monitoring metrics, specify 0.
    Type: Number
  DBPort:
    Default: 5432
    Description: The port the instance will listen for connections on.
    Type: Number
    ConstraintDescription: Must be in the range [1115-65535].
    MinValue: 1150
    MaxValue: 65535
  DBMultiAZ:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
    Description: Specifies if the database instance is a multiple Availability Zone deployment.
    Type: String
  DBName:
    AllowedPattern: ^[a-zA-Z0-9]*$
    Description: Name of the Amazon RDS (PostgreSQL) database.
    MaxLength: 64
    MinLength: 0
    Default: RDSPostgresDB
    Type: String
  DBStorageType:
    Default: io1
    Type: String
    AllowedValues:
      - io1
      - gp2
  CustomDBSecurityGroup:
    Description: ID of the security group (e.g., sg-0234se). One will be created for you if left empty.
    Type: String
    Default: ''
  Subnet1ID:
    Description: The ID of the private subnet in Availability Zone 1.
    Type: AWS::EC2::Subnet::Id
  Subnet2ID:
    Description: The ID of the private subnet in Availability Zone 2.
    Type: AWS::EC2::Subnet::Id
  VPCID:
    Description: ID of the VPC you are deploying Amazon RDS (PostgreSQL)  into (e.g., vpc-0343606e).
    Type: AWS::EC2::VPC::Id
    Default: ''
  EnableEventSubscription:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
    Description: Enables event subscription to Notification List
    Type: String
  NotificationList:
    Type: String
    Default: db-ops@domain.com
    Description: The email notification used to configure an SNS topic for sending CloudWatch alarm and RDS event notifications.
    AllowedPattern: ^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$
    ConstraintDescription: Provide a valid email address.
  EnvironmentStage:
    Type: String
    Description: Designates the environment stage of the associated AWS resource. (Optional)
    AllowedValues:
      - dev
      - test
      - pre-prod
      - prod
      - none
    Default: none
  Application:
    Type: String
    Default: ''
    Description: Designates the application of the associated AWS resource. (Optional)
  ApplicationVersion:
    Type: String
    Description: Designates the specific version of the application. (Optional)
    Default: ''
  ProjectCostCenter:
    Type: String
    Default: ''
    Description: Designates the cost center associated with the project of the given AWS resource. (Optional)
  Confidentiality:
    Type: String
    Default: ''
    Description: Designates the confidentiality classification of the data that is associated with the resource. (Optional)
    AllowedValues:
      - public
      - private
      - confidential
      - pii/phi
      - ''
  Compliance:
    Type: String
    Default: ''
    Description: Designates the compliance level for the AWS resource. (Optional)
    AllowedValues:
      - hipaa
      - sox
      - fips
      - other
      - ''
Resources:
  MonitoringIAMRole:
    Condition: UseEnhancedMonitoring
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - monitoring.rds.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole
  DBSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: !Ref NotificationList
        Protocol: email
  EncryptionKey:
    Condition: UseDatabaseEncryption
    DeletionPolicy: Retain
    Type: AWS::KMS::Key
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - EIAMPolicyWildcardResource
            - EIAMPolicyActionWildcard
            - EKMSKeyEnableKeyRotation #Key rotation would cause the database to become inaccessible
            - W3011 # Quick Starts need to be able to delete all assets upon stack deletion
      cfn_nag:
        rules_to_suppress:
          - id: F19
            reason: Key rotation would cause the database to become inaccessible
          - id: F76
            reason: Conditions are included in the policy to limit its scope
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: !Ref AWS::StackName
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
  EncryptionKeyAlias:
    Condition: UseDatabaseEncryption
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${AWS::StackName}
      TargetKeyId: !Ref EncryptionKey
  DBParamGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Join ['- ', [RDS PostgreSQL Database Instance Parameter Group for Cloudformation Stack, !Ref DBName]]
      Family: !FindInMap [DBFamilyMap, !Ref DBEngineVersion, family]
      Parameters:
        log_rotation_age: 1440
        log_rotation_size: 102400
  RDSDBInstance:
    Type: AWS::RDS::DBInstance
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3011 # Quick Starts need to be able to delete all assets upon stack deletion
    Properties:
      AllocatedStorage: !Ref DBAllocatedStorage
      AutoMinorVersionUpgrade: !Ref DBAutoMinorVersionUpgrade
      AllowMajorVersionUpgrade: !Ref DBAllowMajorVersionUpgrade
      BackupRetentionPeriod: !Ref DBBackupRetentionPeriod
      DBParameterGroupName: !Ref DBParamGroup
      DBInstanceClass: !Ref DBInstanceClass
      DBSubnetGroupName: !Ref RDSDBSubnetGroup
      EnableCloudwatchLogsExports:
        - !If [EnableDBLogExport, postgresql, !Ref AWS::NoValue]
      DBName: !If [DoCreateDatabase, !Ref DBName, !Ref AWS::NoValue]
      Engine: postgres
      EngineVersion: !Ref DBEngineVersion
      KmsKeyId: !If [UseDatabaseEncryption, !GetAtt EncryptionKey.Arn, !Ref AWS::NoValue]
      MasterUserPassword: !Ref DBPassword
      MasterUsername: !Ref DBUsername
      MaxAllocatedStorage: !Ref DBMaxAllocatedStorage
      MonitoringInterval: !Ref DBMonitoringInterval
      MonitoringRoleArn: !If [UseEnhancedMonitoring, !GetAtt MonitoringIAMRole.Arn, !Ref AWS::NoValue]
      Port: !Ref DBPort
      PubliclyAccessible: false
      StorageType: !Ref DBStorageType
      Iops: !If [DBProvisionedIops, !Ref DBIops, !Ref AWS::NoValue]
      StorageEncrypted: !If [UseDatabaseEncryption, !Ref DBAllocatedStorageEncrypted, !Ref AWS::NoValue]
      MultiAZ: !Ref DBMultiAZ
      Tags:
        -
          Key: Name
          Value: !Sub RDSDB-${AWS::StackName}
        -
          Key: EnvironmentStage
          Value: !Ref EnvironmentStage
        -
          Key: Application
          Value: !Ref Application
        -
          Key: ApplicationVersion
          Value: !Ref ApplicationVersion
        -
          Key: ProjectCostCenter
          Value: !Ref ProjectCostCenter
        -
          Key: Confidentiality
          Value: !Ref Confidentiality
        -
          Key: Compliance
          Value: !Ref Compliance
      VPCSecurityGroups:
        - !If [CreateSecurityGroup, !Ref RDSSecurityGroup, !Ref CustomDBSecurityGroup]
    UpdateReplacePolicy: Snapshot
  RDSDBSubnetGroup:
    Properties:
      DBSubnetGroupDescription: Subnets available for the Amazon RDS (PostgreSQL) database instance
      SubnetIds:
       - !Ref Subnet1ID
       - !Ref Subnet2ID
    Type: AWS::RDS::DBSubnetGroup
  RDSSecurityGroup:
    Condition: CreateSecurityGroup
    Properties:
      GroupDescription: Allow access to database port
      SecurityGroupEgress:
        -
          CidrIp: 0.0.0.0/0
          FromPort: -1
          IpProtocol: -1
          ToPort: -1
      SecurityGroupIngress:
        -
          CidrIp: !Ref DBAccessCIDR
          FromPort: !Ref DBPort
          IpProtocol: tcp
          ToPort: !Ref DBPort
      VpcId: !Ref VPCID
      Tags:
      - Key: Name
        Value: !Sub RDSSecurityGroup-${AWS::StackName}
    Type: AWS::EC2::SecurityGroup
  RDSSecurityGroupIngress:
    Condition: CreateSecurityGroup
    Properties:
      GroupId: !GetAtt RDSSecurityGroup.GroupId
      IpProtocol: -1
      SourceSecurityGroupId: !Ref RDSSecurityGroup
      Description: Self Reference
    Type: AWS::EC2::SecurityGroupIngress
  CPUUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref DBSNSTopic
      AlarmDescription: CPU_Utilization
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref RDSDBInstance
      MetricName: CPUUtilization
      Statistic: Maximum
      Namespace: AWS/RDS
      Threshold: 80
      Unit: Percent
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Period: 60
      EvaluationPeriods: 5
      TreatMissingData: notBreaching
  MaxUsedTxIDsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref DBSNSTopic
      AlarmDescription: Maximum Used Transaction IDs
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref RDSDBInstance
      MetricName: MaximumUsedTransactionIDs
      Statistic: Average
      Namespace: AWS/RDS
      Threshold: 600000000
      Unit: Count
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Period: 60
      EvaluationPeriods: 5
      TreatMissingData: notBreaching
  FreeLocalStorageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref DBSNSTopic
      AlarmDescription: Free Local Storage
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref RDSDBInstance
      MetricName: FreeLocalStorage
      Statistic: Average
      Namespace: AWS/RDS
      Threshold: 5368709120
      Unit: Bytes
      ComparisonOperator: LessThanOrEqualToThreshold
      Period: 60
      EvaluationPeriods: 5
      TreatMissingData: notBreaching
  DatabaseInstanceEventSubscription:
    Condition: EventSubscription
    Type: AWS::RDS::EventSubscription
    Properties:
      EventCategories:
      - availability
      - configuration change
      - deletion
      - failover
      - failure
      - maintenance
      - notification
      - recovery
      SnsTopicArn: !Ref DBSNSTopic
      SourceIds:
        - !Ref RDSDBInstance
      SourceType: db-instance
  DBParameterGroupEventSubscription:
    Condition: EventSubscription
    Type: AWS::RDS::EventSubscription
    Properties:
      EventCategories:
        - configuration change
      SnsTopicArn: !Ref DBSNSTopic
      SourceIds:
        - !Ref DBParamGroup
      SourceType: db-parameter-group
Outputs:
  DBName:
    Description: Amazon RDS (PostgreSQL) database name
    Value: !Ref DBName
  DBUsername:
    Description: Amazon RDS (PostgreSQL) database username.
    Value: !Ref DBUsername
  RDSEndPointAddress:
    Description: Amazon RDS (PostgreSQL) endpoint
    Value: !GetAtt RDSDBInstance.Endpoint.Address
  RDSEndPointPort:
    Description: Amazon RDS (PostgreSQL) endpoint port
    Value: !GetAtt RDSDBInstance.Endpoint.Port
  RDSEndPoints:
    Description: Amazon RDS (PostgreSQL) write endpoint
    Value: !Sub ${RDSDBInstance.Endpoint.Address}:${RDSDBInstance.Endpoint.Port}/${DBName}
  RDSEncryptionKey:
    Condition: UseDatabaseEncryption
    Description: The alias of the encryption key created for RDS
    Value: !Ref EncryptionKeyAlias
